#!/usr/bin/env php
<?php
/**
 * this source file is gearman
 *
 * author: shuc <shuc324@gmail.com>
 * time:   2016-05-29 23-48
 */
require_once("./bootstrap/autoload.php");

(new App\Application())->run();